### ISSUE TITLE
change standard dangerfile not to fail on missing labels

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#104]
Every time a pull request is created, it will initially have no lablels. That means that every single pull request will trigger the Dangerfile check that complains:

    Please add labels to this Pull Request

This is annoying on its own. But in order to fix this build error, a contributor is required to push a change to the branch to trigger a rebuild. (Oh, and there's no way for the contributor to know that this is the "right" way to trigger a rebuild).

This is a terrible user experience, especially for first time contributors.

We should either:
- remove this check from our standard Dangerfile, or
- come up with a way to require labels but not have an invisible process for clearing the warning when it's been fixed.

**Comment by damacus** [comment]
Agreed this has been done in most places :+1:

**Comment by PowerSchill** [comment]
Can this be closed?
