### ISSUE TITLE
Remove .rubocop.yml with Dangerfile

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#108]
## Description

If the only thing in the `.rubocop/yml` is Dangerfile
Run the latest cookstyle
Remove `.rubpopo.yml`

**Comment by shreyasbapat** [comment]
Where is this located?

**Comment by damacus** [comment]
Hey!

Thanks for responding, we will have issues across most of our repositories shortly. Though I would ask if you could share the love, and only do a few of them!

Thanks,
Dan

**Comment by shreyasbapat** [comment]
Sure, when I couldn't find the file, I attempted a different issue :D

**Comment by JohnRoesler** [comment]
This and most issues in this repo are generic to all repos in the sous-chefs org. I'd recommend searching or checking in some repos for these files

**Comment by JanStevens** [comment]
DangerFile is not exactly ruby sintax fyi. So letting rubocop run on that file seems dangerous?
