### ISSUE TITLE
Delete branch on PR merge

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#109]
Add the github action to remove merged branches.

**Comment by shreyasbapat** [comment]
Addressed in #113

**Comment by JohnRoesler** [comment]
Unfortunately the documentation in [jessfraz/branch-cleanup-action](https://github.com/jessfraz/branch-cleanup-action) is out of date. I've taken a pass at following the syntax, but the action is not actually deleting the branch at the moment https://github.com/sous-chefs/meta/blob/master/.github/workflows/main.yml 

Something to poke some more and see if maybe it needs a `run` command or if that script is actually working.

**Comment by JohnRoesler** [comment]
Thank you @PowerSchill for solving this one - needed to be run on `closed` action https://github.com/sous-chefs/meta/blob/master/.github/workflows/main.yml#L5

**Comment by PowerSchill** [comment]
Reopening so I can track implementation.

**Comment by majormoses** [comment]
Github now supports [this natively](https://help.github.com/en/articles/managing-the-automatic-deletion-of-branches) but [did not expose](https://github.com/google/go-github/issues/1245) the setting in the v3 or v4 api.

**Comment by JohnRoesler** [comment]
I can confirm it's there in the settings. So much for a cool GitHub action to take care of it

**Comment by PowerSchill** [comment]
Yeah, I saw that but also noticed the terraform provider for GitHub didn't seem to support that setting. The actions do open up possibilities for other things so as a learning experience it was valuable.

**Comment by xorima** [comment]
all merged

**Comment by JohnRoesler** [comment]
We decided to use the github action route to auto delete branches as the github api does not have the delete branch setting exposed and so we can't work that into the terraform provider
