### ISSUE TITLE
[RFC] Web Presence / Domain Name

### ISSUE THREAD

**Issue by rex** [sous-chefs/meta#11]
Greetings Brigade!

The purpose of this RFC is to start the conversation about our organization's presence on the web.
## Proposal 
- **Important**: We will acquire a real, grown-up domain name for our organization. 
  - Side note: www.chefbriga.de is available and just $12.50 :smile: 
- **Not as important**: We'll have our very own (preferably simple) web site at the root of the domain name.

I'm sorry it's so terse, but I didn't want to impose any personal bias into it. 

Eager to hear the brigade's thoughts in this area!

**Comment by juliandunn** [comment]
Domain name is great, and even if it's just pointing to a GitHub Pages site that's good enough.

Shall I talk to our graphic designer about a logo?

**Comment by dblessing** [comment]
:+1: @juliandunn That would be great.

**Comment by rex** [comment]
:+1: @juliandunn I second that! It would be fantastic and much appreciated!

**Comment by josephholsten** [comment]
Domain name is done: https://chefbrigade.io

Creating a different ticket for logo: #26
