### ISSUE TITLE
Dangerfile should use failure instead of fail

### ISSUE THREAD

**Issue by xorima** [sous-chefs/meta#110]
On the repo, ensure that `Dangerfile` matches https://github.com/sous-chefs/repo-management/blob/master/Dangerfile

**Comment by JohnRoesler** [comment]
@tas50 should this now be `raise`? I've seen it in a few prs

**Comment by tas50** [comment]
Rubocop is going to want raise. If that's not going to work with Danger and CI then we should get that pushed out in .rubocop.yml files

**Comment by JohnRoesler** [comment]
@Xorima 👆

**Comment by xorima** [comment]
Ok I will add this to my todo list today

**Comment by xorima** [comment]
Closing now as every single cookbook repo is done, every single issue is now closed.
