### ISSUE TITLE
Investigate options for standardizing common files

### ISSUE THREAD

**Issue by JohnRoesler** [sous-chefs/meta#114]
### :speaking_head: Foreword

Thank for taking the time to fill this feature request fully. Without it we may not be able to , and the issue may be closed without resolution.

## :person_frowning: Problem Statement

it would be nice not to have to mass PR all the repos when you want to make a change to set of common files across all.

## :grey_question: Possible Solution

possibly a terraform provider exist that would allow us to maintain common files in the terraform config?

## :heavy_plus_sign: Additional context

Some examples of common files: GitHub actions, danger files

**Comment by xorima** [comment]
All Generic files are now handled by github-file-manager,
