### ISSUE TITLE
[RFC] README.md template

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#12]
a nice-looking standard template for `README.md`s. Has 
- [ ] nice centered logo
- [ ] centered badges
- [x] eg "about mongodb"
- [x] "from chef brigade"
- [ ] defined structure
- [ ] bake the logo and front-matter into the overview.md file.

without stretching food metaphors beyond the breaking point

**Comment by josephholsten** [comment]
This should probably go in https://github.com/chef-brigade/cookbook-skeleton

**Comment by tas50** [comment]
centered?

**Comment by josephholsten** [comment]
I swear I've seen centered badges. I may be insane.

**Comment by zuazo** [comment]
Here is an example of centered badges:

https://github.com/badges/shields/blob/master/README.md

![shields_io_centered_badges](https://cloud.githubusercontent.com/assets/1878434/23586111/ec475cb0-018e-11e7-8189-f08cc006c6bc.png)

The code:

```html
<p align="center">
    <a href="https://www.gratipay.com/Shields/">
        <img src="https://img.shields.io/gratipay/team/shields.svg"
             alt="Gratipay">
    </a>
    <a href="https://npmjs.org/package/gh-badges">
        <img src="https://img.shields.io/npm/v/gh-badges.svg"
             alt="npm version">
    </a>
    <a href="https://travis-ci.org/badges/shields">
        <img src="https://img.shields.io/travis/badges/shields.svg"
             alt="build status">
    </a>
</p>
```

**Comment by shoekstra** [comment]
I think we should stick to markdown only and not mix in HTML, at least until the supermarket can render it properly (first thing that comes to mind is how HTML tables are rendered in supermarket, we'd want to avoid that coming from a template).

**Comment by damacus** [comment]
I'm going to close this one down. Until we know we can make some good progress on it
