### ISSUE TITLE
Create GitHub Pages repo and configure site with custom domain

### ISSUE THREAD

**Issue by rex** [sous-chefs/meta#19]

**Comment by rex** [comment]
Done and done! Check out our new home at https://chefbrigade.io! :smiley: :rocket: 

_Note:_ The design is just something I threw together. I **do not expect** it to last very long. I just wanted to get something up that wasn't a blank page or `Hello World`.

**Comment by zuazo** [comment]
@rex thanks for all your work with the domain, CloudFlare, GitHub Pages, Apps and all that boring stuff :wink:

**Comment by rex** [comment]
@zuazo Thanks :D Now we can get on with building awesome things instead of worrying about this stuff.
