### ISSUE TITLE
Configure Route53 DNS management for chefbrigade.io

### ISSUE THREAD

**Issue by rex** [sous-chefs/meta#20]

**Comment by rex** [comment]
**Update**: This is in progress. I have pointed the nameservers to AWS Route53 endpoints and will be adding more resource sets as necessary until everything is in place.

**Comment by rex** [comment]
I've now added a `TXT` record for Google Apps domain verification as well as all necessary `MX` records to enable mail.

**Comment by rex** [comment]
This is evidence of my lack of familiarity with CloudFlare. Route53 is entirely unnecessary since CF assumes control of DNS settings. Awaiting completion of propagation to CF before deleting Route53 zones and closing issue.

**Comment by rex** [comment]
Unfortunately I didn't have the presence of mind to check the TTL before I pointed the nameservers to Route53 which set them _extremely_ high. Makes sense, since they usually rarely change. In our case, though, it's a major PITA. 

I am not going to close this issue until global DNS fully propagates. On principle, really. 

You can check the current state of global DNS propagation here: https://www.whatsmydns.net/#NS/chefbrigade.io

**Comment by k3ypad** [comment]
Running through all the issues in this repo, on a quick look it appears that CF has control now

**Comment by josephholsten** [comment]
@rex do you mind tossing that config into a terraform file, http://www.terraform.io/docs/providers/cloudflare/r/record.html should be the right resource

**Comment by rex** [comment]
@k3ypad Indeed the only location still reporting the old nameservers is in Karachi, Pakistan. I think it's safe to say it's propagated.

@josephholsten I'll do that straight away and create a wiki page for it. Unless I should create a new repo like `brigade-config` with a `terraform` directory in it and put it there...?
