### ISSUE TITLE
Service monitoring for site, DNS, email

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#21]
Now that we've got a public site, I'd like it not to go down.

Any suggestions besides Pingdom? I like server density, but it's overkill for what we need today.

**Comment by k3ypad** [comment]
R53 is pretty much the same, cheap enough too: http://aws.amazon.com/route53/pricing/#Health_Checks

**Comment by josephholsten** [comment]
@k3ypad how much is your commission these days?

**Comment by rex** [comment]
Oooh sick burn :fire: 

$0.75 per health check per month is a little rich for my blood. I'd rather spend $5/mo on a DO droplet and use/write an OSS app to do monitoring.

**Comment by miketheman** [comment]
I've been playing with statuscake.com - seems nice.

**Comment by rex** [comment]
StatusCake looks nice, that's a solid option. 

Other open source options:

https://github.com/hashicorp/consul
https://github.com/fzaninotto/uptime
https://github.com/arachnys/cabot
https://github.com/martinrusev/amonone
https://github.com/eBay/restcommander

**Edit:** I forgot the longtime favorites. Nagios, Munin, Cacti, and Zabbix.

**Comment by josephholsten** [comment]
I meant to say this is for the minimal external checks to make sure our stuff is in the world. A DNS check and a http://hostname check should be sufficient. Moved to https://github.com/chef-brigade/ops/issues/2

We can build complex monitoring once that's done. Moved to https://github.com/chef-brigade/ops/issues/3
