### ISSUE TITLE
Anyone want to maintain solr?

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#22]
Supermarket:
    https://supermarket.chef.io/cookbooks/solr

Github:
    https://github.com/dwradcliffe/chef-solr

Does anyone want to maintain this cookbook? It's only claiming to support solr 4, so it's not a reasonable choice for new installations today. I'd like someone who's ready to handle the existing pull requests and will put in the effort to support solr 5.

**Comment by dblessing** [comment]
I'm interested in helping. We'll be needing solr very shortly. It may be a few weeks before I can dedicate time though.

**Comment by rex** [comment]
It's a popular technology and would be good to bring it into the brigade. I am occupied with mongo of course but definitely think someone in the brigade should take it on. 

If @dblessing is willing to be the lead maintainer starting in a few weeks then I can take some time assessing the current state of its tests and issues so he can hit the ground running. Might even take that long just to bring it under our umbrella.

**Comment by zarry** [comment]
My company uses Solr in fact it is the last piece of our infrastructure that isn't automated.  I have poked around that cookbook a bit.  

I would consider taking ownership of solr.  The caveat being my company sticks with solr and doesn't move to elastic search or an aws service.

**Comment by josephholsten** [comment]
@zarry well, I wouldn't consider solrcloud in 4, way too much maintenance headache. Either old-style primary-replica replication like in 3 or earlier, or you'll want 5.

If you're interested in maintaining, could you connect with the existing maintainer? They probably have their own expectations for handing off a cookbook. Once we've got someone ready to be the official maintainer, we can move it under the brigade.

**Comment by dblessing** [comment]
Sent a message to the current maintainer.

**Comment by zarry** [comment]
@dblessing @josephholsten Thank you for reaching out.  I actually don't think I will be able to take ownership of the solr cookbook.  It sounds like we are strongly considering moving away from solr for various reasons.  

I don't mind helping out a bit with the specific cookbook but as far as ownership goes we may want to find someone else, maybe @dblessing

**Comment by josephholsten** [comment]
might want to contact https://github.com/vkhatri/chef-solrcloud as well

**Comment by josephholsten** [comment]
I'm closing this until an actual need to pick up solr exists, or a maintainer actively approaches us to help.
