### ISSUE TITLE
Anyone want to maintain tar?

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#23]
Supermarket:
    https://supermarket.chef.io/cookbooks/tar

Github:
    https://github.com/gofullstack/tar-cookbook

This cookbook seems like it should be a core resource. [ark](https://supermarket.chef.io/cookbooks/ark) is really useful, but very magical. This is a building-block cookbook, so it's going to have a higher standard for backwards compatibility. 

If we adopt this, I'd like brigade maintainers to consider using it whenever a tarball is encountered. If we're not comfortable encouraging it as the standard way of handling tarballs, then we shouldn't adopt it.

**Comment by rex** [comment]
That would be awesome, I'd love to take that one on. Absolutely agree on both points.
- It's a core UNIX utility so expectations will be understandably _very_ high
- If we adopt it we should be using it in all other cookbooks when necessary

**Comment by josephholsten** [comment]
alternatively, we might want to prefer using https://github.com/reset/libarchive-cookbook, which uses the excellent http://libarchive.org/

**Comment by rex** [comment]
It looks like a definite improvement but I'm not sure I see which direction you want to go. Are you suggesting that we implement `libarchive` under the hood of the `tar` cookbook? Or simply pass on the `tar` cookbook altogether?

**Comment by josephholsten** [comment]
I'm closing this since we don't have any strong need for this project.
