### ISSUE TITLE
hubot for slack

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#24]
because everyone needs more mustache

**Comment by rex** [comment]
+50. Do you want to just fire this up on Heroku? Or are we discovering another use case for moving to DigitalOcean et al?

**Comment by josephholsten** [comment]
heroku unless there's a need for a real server

**Comment by rex** [comment]
SGTM (sounds good to me... is that a thing?)

**Comment by miketheman** [comment]
Tossing out lita as a ruby-friendly replacement for hubot (been having a great time with it, and it's _not_ coffeescript.
https://www.lita.io/

**Comment by rex** [comment]
I'm good with either/or. Lita looks really cool, though i'm more familiar with Hubot. Whatever you guys want!

**Comment by josephholsten** [comment]
moved to https://github.com/chef-brigade/ops/issues/4 and https://github.com/chef-brigade/ops/issues/5

**Comment by josephholsten** [comment]
There's no problem with running both for a bit. Get em both up, we can destroy the less useful one later.
