### ISSUE TITLE
What license should we use?

### ISSUE THREAD

**Issue by zuazo** [sous-chefs/meta#25]
OK. So it seems that we are going to release some documentation and some code examples / recommendations.

Which license should use for them? Like many of you, I usually use [Apache License](http://www.apache.org/licenses/LICENSE-2.0) for cookbooks. But I am open to other suggestions. I know it's not a copyleft license.

**Comment by dblessing** [comment]
:+1: for Apache license http://www.apache.org/licenses/LICENSE-2.0

**Comment by zarry** [comment]
:+1: for Apache

**Comment by rex** [comment]
A lot of people in the world much smarter than me swear by the Apache license and I'm nobody to question the status quo on this. :+1: for Apache.

**Comment by josephholsten** [comment]
I'd especially like to include a link to http://choosealicense.com/, so people can make an informed decision.

Apache seems like a great default.

Someone want to write it up?

**Comment by zuazo** [comment]
Sorry for the delay. Closing in favor of #28.
