### ISSUE TITLE
Transfer Etcd cookbook on Supermarket over to Sean OMeara

### ISSUE THREAD

**Issue by spheromak** [sous-chefs/meta#34]
Sean Is taking it over for a full rework. We moved the repo over to him yesterday, but I need someone who has access to move the supermarket name over too.

**Comment by someara** [comment]
Ping for supermarket transfer... got a 3.0.0 release ready to cut =)

**Comment by someara** [comment]
@josephholsten can you transfer etcd to someara ?

**Comment by josephholsten** [comment]
@someara doing it now

**Comment by josephholsten** [comment]
@someara I transferred ownership to you. If you were wanting this to stay under the chef-brigade banner, feel free to transfer it back and just push to it.

**Comment by someara** [comment]
Thanks!
