### ISSUE TITLE
tool for checking compliance with standards

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#37]
it's great to have a list of standards for cookbooks, but a tool that actually can do the verification is even better:

Here are the things we want a cookbook to follow:
- https://github.com/chef-brigade/meta/blob/master/transfering-a-cookbook.md
- https://github.com/chef-cookbooks/community_cookbook_documentation

specifically:
- `Berksfile`
- `CHANGELOG.md`
  - must exist
  - must follow http://keepachangelog.com/en/0.3.0/ ?
- `CODE_OF_CONDUCT.md`
  - must exist
- `CONTRIBUTING.md`
  - must exist
- `Gemfile`
  - berkshelf
  - chefspec
  - cookstyle
  - foodcritic
  - stove
  - test-kitchen
- `LICENSE.md`
  - must exist
  - no requirement for which licenses are allowed
- `README.md`
  - must exist
  - link to chef-brigade
- `metadata.rb`
  - `source_url "https://github.com/chef-brigade/#{name}-cookbook" if respond_to?(:source_url)`
  - `issues_url "https://github.com/chef-brigade/#{name}-cookbook/issues" if respond_to?(:issues_url)`
  - `maintainer 'Chef Brigade'`
  - `maintainer_email 'help@chefbrigade.io'`
- `.kitchen.yml`
- cookstyle
  - must pass
- foodcritic
  - must pass

Open Questions
- [ ] should we avoid a `Gemfile` and trust ChefDK
- [x] do we need [`stove`](https://github.com/sethvargo/stove)
- [ ] shall we just remove the `-cookbook` suffix
- [ ] shall we use [`community_cookbook_releaser`](https://rubygems.org/gems/community_cookbook_releaser/) to make the release bumps.
- [x] shall we use [`knife-cookbook-doc`](https://github.com/realityforge/knife-cookbook-doc) [Nope -jh]

**Comment by josephholsten** [comment]
we're not all agreed about the `#{name}-cookbook` thing

**Comment by zuazo** [comment]
And:
- [InSpec](https://www.chef.io/inspec/) over Serverspec

Nowadays, I for one think it's better to use ChefDK instead of bundler. And use bundler only when you need specific gem not included in ChefDK. But maybe it is a good idea to have a _Gemfile_ just in case.

There is also a gem called [`community_cookbook_releaser`](https://rubygems.org/gems/community_cookbook_releaser/). But it seems to be a simple (and undocumented) script to make the release bumps.

**Comment by josephholsten** [comment]
related: make sure https://github.com/chef-brigade/cookbook-skeleton complies

**Comment by mengesb** [comment]
I'm ok with most of the `metadata.rb` things except that is it really necessary to identify cookbook in the name itself? Won't the vast majority of things be cookbooks, thus making it a bit redundant?

So far as bundler - would much rather standardize on chefdk

Definitely OK with cookstyle defaults for rubocop and foodcritic inclusion

test-kitchen is a MUST

suggest inspec over serverspec or chefspec, however at least ONE *spec should be included. I'd agree the strong preference should be for inspec

Stove i'm a bit on the fence about. Seems to be a good idea, i just haven't used it. so lets give it a go!

**Comment by josephholsten** [comment]
from https://github.com/chef-brigade/meta/issues/12, I noticed mention of https://github.com/realityforge/knife-cookbook-doc. thoughts?

**Comment by josephholsten** [comment]
@zuazo what's the easiest way to check if a cookbook is using inspec?

**Comment by mengesb** [comment]
@josephholsten Seems realityforge/knife-cookbook-doc is going or has gone stale, there's differences from the originally cited work. It's great to have standards in documentation, wholeheartedly agree! Seems though this might be questionable though.

**Comment by Sliim** [comment]
@josephholsten,

> @zuazo what's the easiest way to check if a cookbook is using inspec?

Maybe looking for `kitchen-inspec` in `Gemfile`, or this should be present in `.kitchen.yml`:

```
verifier:
  name: inspec
```

Update:
There is also these files/directories:
- `test/integration/default/inspec.yml`
- `test/integration/default/controls`

But these are present only if the cookbook comes with its own profile.

**Comment by zuazo** [comment]
Also, checking if the `"#{test_base_path}/#{suite_name}/inspec"` directory exists. For example: `"test/integration/default/inspec/*_spec.rb"`.

More paths can be added in the `.kitchen.yml` using the `inspec_tests` configuration option:

``` yaml
suites:
  - name: default
    verifier:
      inspec_tests:
      - /path/to/local/folder
```

Or using the `path` subkey:

``` yaml
suites:
  - name: default
    verifier:
      inspec_tests:
        path: path/to/local/folder
```

**Comment by tas50** [comment]
@zuazo The community cookbook releaser is just a simple script I put together to speed up releasing the chef community cookbooks. It's entirely my workflow and super basic. Only works on chef stuff at the moment. It could probably be expanded to do the same thing in a more generic way. The biggest issue would be detecting the github org based on the source_url in the metadata.

**Comment by josephholsten** [comment]
I've put a first pass implementation over here: https://github.com/chef-brigade/cb-foodcritic-rules/pull/1

I'd absolutely ❤️ feedback about checks to add, remove or modify

**Comment by josephholsten** [comment]
ok, sc-foodcritic-rules has been added to apache2, so it's functioning.

Are there any rules in here that we need to move over there? are there any other kinds of validation we want?

**Comment by tas50** [comment]
As we go about adding FC rules lets try to consider adding them upstream rather than here. FC itself could always use improvement
