### ISSUE TITLE
set up email at sous-chefs.org

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#39]
We'd like to have a maintainer email at sous-chefs.org. Google apps?

**Comment by shortdudey123** [comment]
Maybe we can try under the org section? 
https://www.google.com/nonprofits/eligibility/

**Comment by shortdudey123** [comment]
NVM on the org side... `Organizations must be recognized by the IRS as tax-exempt 501(c)(3) organizations formed for charitable, educational, religious, literary, scientific, or other tax-exempt purposes.`

Unless we want to go through that process

**Comment by rshade** [comment]
this should probably be a mailing list right? so the basic service might help.

**Comment by josephholsten** [comment]
ok, j@ and help@ have been set up. Further account setup will occur in other tickets as needed.
