### ISSUE TITLE
Gitter.im

### ISSUE THREAD

**Issue by zarry** [sous-chefs/meta#4]
Can one of the group owners setup a gitter.im room for chef-brigade or grant access?  I think that might be a better way to foster some discussion both about our group in general and the cookbooks we manage.

https://gitter.im

**Comment by luishdez** [comment]
Yep, gitter or slack would be much better…

@josephholsten I've requested grant access to gitter but we need your approval :)

Update: ok I think it's already set.

**Comment by josephholsten** [comment]
dun

**Comment by rex** [comment]
@josephholsten @zarry @luishdez I am in love with the concept of using Slack. It's not a free solution but it's cheap enough that I can take care of it for the foreseeable future. 

What do you guys think about HipChat? Atlassian just made it a free product and it would make it easier to monitor alongside chat tools that we all certainly use in our standard day-to-day.

**Comment by zarry** [comment]
@rex I use hipchat in my office so I have a slight lean towards that, but overall I don't mind one way or the other if it ends up being slack, gitter.im or hipchat.  

I think the lowest barrier to entry for a community member to communicate with us is the ultimate goal.  Assuming slack provides a similar web ui like gitter?  Does it require an additional login credentials?  Does it work with github auth like gitter?

**Comment by rex** [comment]
@zarry Slack _does_ provide a web UI, though it does require its own login credentials and does not support Github auth. IMO it's simply a much sexier cousin of HipChat that is much more fully-featured/mature. I think HipChat would provide us everything that we might need in terms of communication and IMO is a better alternative than Gitter. I suppose it's on principle that I'm not a huge fan of Gitter - I feel that what we're doing is a collaborative effort to create something really fantastic and HipChat/Slack feels more "permanent" for lack of a better word. In other words, Gitter just seems too... informal. In my opinion, of course.

**Comment by josephholsten** [comment]
ok, I registered for https://chef-brigade.slack.com/, and I'll be getting us a domain name in a day or so.

**Comment by rex** [comment]
@josephholsten That's great news! :smile: Let us know when you invite us to the organization so we can set up our accounts!

**Comment by josephholsten** [comment]
@rex I invited you manually, trying to work out a sane way to do this en-masse

**Comment by rex** [comment]
Awesome, I'll set up my account shortly. I agree it will be kind of a pain. Their "invite to team" functionality should be pretty straightforward but it is a lot of email addresses to add. Let me know if I can be of any help!

**Comment by josephholsten** [comment]
to @zarry's point, it looks like slack doesn't provide github auth. But it _does_ let me run this: https://github.com/auth0/auth0-slackin so people can register themselves.

**Comment by zarry** [comment]
That works for me. Let me know when you have the page up and I can sign up.

**Comment by josephholsten** [comment]
ok, please give this a look: https://github.com/chef-brigade/meta/pull/9
