### ISSUE TITLE
Consistent labels

### ISSUE THREAD

**Issue by tas50** [sous-chefs/meta#41]
It would be really nice to apply consistent labels across the repos to make triage easy at an org level. We're doing this in chef-cookbooks now and it's been super handy.

**Comment by damacus** [comment]
Suggested tags:
- help wanted
- easy
- failing_test

**Comment by shortdudey123** [comment]
`feedback_requested`?

**Comment by tas50** [comment]
These are the ones we're using in Chef. I lifted most of them from some other project.

https://github.com/chef-cookbooks/community_cookbook_tools/blob/master/config/github_labels.json

**Comment by shortdudey123** [comment]
Fancy :) 
I would add `Breaking Change` to that list too

**Comment by svanzoest** [comment]
I am using the following in `apache2`:

* Major package versions: `apache/2.2`, `apache/2.4`
* Issue types: `bug`, `enhancement`. `question`
* Issue states:  `duplicate` , `in progress`, `invalid` , `wontfix`
* Operating System: `os/amazon`, `os/arch`, `os/centos`, `os/debian`, `os/fedora`, `os/freebsd`, `os/macos`, `os/redhat`, `os/scientific`, `os/suse`, `os/ubuntu`
* 3rd party feature parity/compatibility: `parity/asf`, `parity/chef`, `parity/iptables`, `parity/security`

**Comment by tas50** [comment]
I think a lot of them are going to be repo specific. A lot of those that @svanzoest have are obviously apache specific and very useful for sorting. You can tell the app to not remove things it doesn't know about, which would allow those to stay.
