### ISSUE TITLE
Interest in maintaining the Varnish cookbook?

### ISSUE THREAD

**Issue by martinb3** [sous-chefs/meta#42]
hey folks -- would we be interested in maintaining the varnish cookbook? We had been maintaining at Rackspace, but we haven't used it nearly as much in the last year as previously; we've had a lot of PRs and issues filed where submitters are very opinionated, but as reviewers, we haven't been (due to lack of use).

Supermarket link: https://supermarket.chef.io/cookbooks/varnish

Github link: https://github.com/rackspace-cookbooks/varnish

/CC @jtimberman @tas50 in case they want to chime in on Chef or others who may want to maintain it.

**Comment by rshade** [comment]
Would you also be willing to help maintain?

**Comment by rshade** [comment]
https://github.com/sous-chefs/meta/blob/master/transfering-a-cookbook.md

**Comment by rshade** [comment]
@martinb3 do you want to transfer the repo to us?

**Comment by tas50** [comment]
I've never personally used Varnish so I don't have a huge desire to take point on maintaining it. If there's someone that's super eager to do so they should become the maintainer through Sous Chefs. If there isn't a person interested though it will just languish here, which isn't really what we want in the Sous Chefs.

**Comment by martinb3** [comment]
I'm happy to do things either way. We're kind of in the same boat as @tas50, in that we're not really doing a ton with it right now either. I don't know if he's a member here, but @ryanjarv has also been contributing a bunch to it recently -- and may be interested in joining us.

**Comment by rshade** [comment]
Yep, I am cool with primarying it, if I get some side support from you guys. Q/A and stuff. @tas50 already knows how much of a pita I can be from haproxy though.

**Comment by RyanJarv** [comment]
Hey all, I plan on continuing to contribute the cookbook and can help on the QA side. I don't want to commit to anything longterm, but for at least the foreseeable future I can help out.

**Comment by rshade** [comment]
@martinb3 ready to do some transferring?

**Comment by martinb3** [comment]
Yep! Let's do it @rshade. I've initiated the transfer, but I'm not an admin over on this side, so I can't give commit access, invite @RyanJarv, and whatnot. I've created https://github.com/orgs/sous-chefs/teams/varnish.

**Comment by RyanJarv** [comment]
@rshade would be interested if you have any opinions on my recent rewrites. The 3.0 cookbook was released somewhat recently and I don't think many people have adopted it yet so If there's any breaking changes that we want to do might not be a bad time for that.

**Comment by rshade** [comment]
@RyanJarv I think they look good. I don't have anything breaking yet.

**Comment by rshade** [comment]
@martinb3 did you transfer in supermarket also?

@RyanJarv do I need to add you to terraform as a maintainer?

**Comment by RyanJarv** [comment]
If you want to, either way is fine with me. I was just making pull requests before fyi.

**Comment by martinb3** [comment]
@rshade Yes, I did also add sous-chefs to Supermarket. I didn't make it the primary (I wasn't sure how sous-chefs interacted with Supermarket and wanted to come back here and read more).

**Comment by rshade** [comment]
@josephholsten @tas50 can you help out on that? ^^

**Comment by rshade** [comment]
https://github.com/sous-chefs/terraform-github-org/pull/13

**Comment by rshade** [comment]
@martinb3 do you want me to add you to the varnish repo definition?

**Comment by martinb3** [comment]
@rshade Sure, that would be great. I can't commit a ton of time, but I'll help out where possible 👍

**Comment by martinb3** [comment]
I think we've taken care of all of these except maybe updating the README on the repo -- I'm good to close this when you all are 👍
