### ISSUE TITLE
Add board to the page

### ISSUE THREAD

**Issue by tas50** [sous-chefs/meta#49]
We need to add information on the structure of the org and the current board to this doc and probably a page on the website that doesn't yet exist

**Comment by damacus** [comment]
see #51

**Comment by josephholsten** [comment]
So we need: 
- current members
- responsibilities
- election process

Anything else?

**Comment by damacus** [comment]
How to become a sous chef?

**Comment by josephholsten** [comment]
@tas50 want to throw together some strawman language we could review?

**Comment by josephholsten** [comment]
@damacus @tas50 how does #63 look?
