### ISSUE TITLE
Teams Update & Repo Tidy

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#52]
Remove Teams
- [x] Commis

Make Public
- [x] Chef de partie

Add to Terraform
- [x] apache2
- [x] Board
- [x] bsdcpio
- [x] Chef de partie
- [x] chef-compliance
- [x] dhcp
- [x] edelight-chef-mongodb-transition
- [x] graphite
- [x] haproxy
- [x] mongodb
- [x] meta
- [x] nano
- [x] postgresql
- [x] samba
- [x] sc-generator
- [x] sc-foodctiric-rules
- [x] selinuxpolicy
- [x] smartmontools
- [x] snort
- [x] sous-chefs.github.org
- [x] sysctl
- [x] openvpn
- [x] ossec
- [x] unbound

Remove Repos
- [x] infra-tf-resources
- [x] infra-chef-cfg
- [ ] ops

**Comment by josephholsten** [comment]
I'm okay with removing these things

**Comment by tas50** [comment]
Ship it

**Comment by damacus** [comment]
There are  still a couple of outstanding issues in Ops we need to look at this week.
