### ISSUE TITLE
Update code of conduct doc

### ISSUE THREAD

**Issue by tas50** [sous-chefs/meta#57]
We need to update this doc to point to the chef CoC

**Comment by josephholsten** [comment]
current version is here: https://github.com/sous-chefs/meta/blob/master/docs/code-of-conduct.md

What exactly should we change?

**Comment by josephholsten** [comment]
per tas50
- copy the chef doc
- change the names
- done

**Comment by damacus** [comment]
Moved to https://github.com/sous-chefs/sous-chefs/issues/11
