### ISSUE TITLE
doc website

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#59]
we should have a friendly website showing off our procedures.

**Comment by josephholsten** [comment]
strawman proposal:
- convert this repo to github pages
- review existing markdown files to verify they render more or less correctly

**Comment by rshade** [comment]
please throw some input in here

**Comment by damacus** [comment]
As you may, or may not have noticed I've started moving things into the docs folder for Jekyll.

http://sous-chefs.org/meta/
