### ISSUE TITLE
add sc-foodcritic-rules to transfer docs

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#62]
sc-foodcritic-rules validates that many things are correctly set up. We should include it into the transfer docs, or some other doc.

**Comment by damacus** [comment]
Yep. It makes transfer easier and cleaner.

**Comment by josephholsten** [comment]
One thing I've realized: we've got "standards" that affect code in multiple places. For example, we could add doc for each of these checks, but we also wound want comments about the defaults in sc-generator, and probably will want them elsewhere.
Should we have this bevyhe authoritative home for the standards definitions? I like having them defined right next to the verification code. 
Alternatively we could have them live in meta, and link from here.

**Comment by damacus** [comment]
Docs should live in meta/website. Probably website for access in a standardised place.
