### ISSUE TITLE
doc voting procedure

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#64]
we should really define exactly how we change the governance.

- what needs a vote to be changed?
- who can vote?
- what voting method? ([first-past-the-post](https://en.wikipedia.org/wiki/First-past-the-post_voting), [condorcet](https://en.wikipedia.org/wiki/Condorcet_method), other?)
- what notice needs to be given before a vote? how much time? in what venues?

We absolutely need to have this finalized before chefconf.

**Comment by damacus** [comment]
condorcet please.

**Comment by josephholsten** [comment]
I'm thinking the voting deadline for this season should be http://permatime.com/UTC/2017-05-24/06:00

Thoughts for or against?

**Comment by josephholsten** [comment]
important venues:
- chefconf
- mailing lists
- IRC
- slack

anywhere else?

**Comment by damacus** [comment]
I think we've decided on ChefConf as the primary location with invites into Slack those that cant make it. 

Publicising it in the mailing list.

**Comment by damacus** [comment]
https://github.com/sous-chefs/sous-chefs/issues/12
