### ISSUE TITLE
Syncing common/standard files into all repositories

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#73]
https://github.com/voxpupuli/modulesync

Something like this, or possibly even this might be the answer.

**Comment by josephholsten** [comment]
Is there a particular use case where we're failing? Or where things aren't easy?

**Comment by damacus** [comment]
Things are easy. But I figured we could use an easy setup/sync for the boiler plate files like .delivery/COE_OF_CONDUCT.md etc etc.

**Comment by shoekstra** [comment]
This is a problem I've had since moving to chef (used to use modulesync).

I've solved this using a custom generator and for loop in my cookbook directory.  If someone points me to a model/example SC cookbook I'll try finish up the sc-generator.

**Comment by JohnRoesler** [comment]
[haproxy](https://github.com/sous-chefs/haproxy) is a good one for an example. @shoekstra do you still have the sc-generator stuff around?
