### ISSUE TITLE
Automated releasing

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#74]
Releasing cookbooks should be as easy as

tests complete 
merge
master tests complete
changelog for current version written
Travis releases.

**Comment by damacus** [comment]
https://github.com/voxpupuli/voxpupuli-release-gem

Vox are using this Gem.

**Comment by damacus** [comment]
We can possibly leverage https://github.com/RiotGamesMinions/thor-scmversion

**Comment by damacus** [comment]
or ... https://docs.travis-ci.com/user/deployment/chefsupermarket

**Comment by shoekstra** [comment]
I'm doing it like [this](https://github.com/sbp-cookbooks/sbp_messageanalyzer/blob/master/.travis.yml#L29-L44) using the [stove gem](https://github.com/sethvargo/stove).  It is a work in progress (read: bit hacky right now) but seems to work just fine with a reproducible process.

Current flow is:

* merge PR to master
* `git pull origin master`
* update CHANGELOG.md, update version in `metadata.rb` then `git commit -am "Release v<version in metadata>"`,
* `git push origin master`
* tests run again
* stove does a deploy which:
  * creates a tag
  * pushes to supermarket

Next steps would be to convert to a Rake task/gem and do some checks before attempting a deploy, similar to the voxpupuli-release-gem, like the version in the commit message that gets tagged matches what's in the metadata.rb or that the changelog has been updated.

The downside to this is that you need to regenerate the secret stuff for each repo - there is no org wide secret in Travis yet which would be great.

I looked at using Travis's `chef-supermarket` deploy [like the cpu cookbook does](https://github.com/redguide/cpu/blob/master/.travis.yml#L45-L53), but it still requires someone to push a tag and also I wanted something I could do locally myself, which I can do with stove.

**Comment by damacus** [comment]
That looks pretty much perfect for our use case I think. Well it was along the same lines as I was thinking anyway.


@rshade how's that look?
