### ISSUE TITLE
doc the champion role

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#76]
some projects aren't attached to a single repo, so the person responsible for one isn't (necessarily or merely) a maintainer.

We need to document:
- how does one become a champion
- what are a champion's responsibilities
- what are a champion's authorities
- how does one cease to be a champion

**Comment by josephholsten** [comment]
mostly importantly, we need to document how this person gets a screen-printed t-shirt proclaiming their awesomeness (we need this for maintainers as well)

**Comment by kameghamegha** [comment]
I'd like if champions were expected to at minimum:

1. A page on the sous chefs website, or something similar, as a call to action for the thing they are championing
2. Reach out to current cookbooks for updates or start new cookbooks for the thing they are championing
3. Be the point person for that specific thing they are championing, besides the board.

**Comment by josephholsten** [comment]
this isn't really an active concept any longer. I'd love to see it again, but it's been on hold a while now.
