### ISSUE TITLE
investigate Moya Community Continuity Guidelines v2.0.0

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#78]
Can we work with Moya to create a common shared baseline for both our communities?

https://github.com/Moya/contributors

**Comment by rhealitycheck** [comment]
Do we have enough overlap with Moya to create a common shared baseline? Their docs look good but at what point do we need to tailor it for our own community?

**Comment by josephholsten** [comment]
@rhealitycheck exactly! that's the question I really want an answer to. Not "can we" but "how much should we".
