### ISSUE TITLE
automatically invite new contributors to a GitHub organization team

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#79]
Insipired by:
https://github.com/Moya/Aeryn

I'd like a service that watches all PRs in the github org,
filters for ones that come from a new contributor, 
then creates a PR to https://github.com/sous-chefs/terraform-github-org adding the new contributor

**Comment by damacus** [comment]
As discussed. 

I think we're better off talking as, and to humans to develop relationship with new maintainers rather than let the robot overlords do *everything* in our lives. 

<3
