### ISSUE TITLE
add danger to all cookbooks

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#82]
See here:
http://danger.systems/
https://github.com/danger/danger

**Comment by damacus** [comment]
oooh I like

**Comment by xamebax** [comment]
It looks cool, and doesn't seem like much work? Have we implemented it anywhere?

**Comment by damacus** [comment]
Not yet. Want to give it a try @xamebax ?

**Comment by xamebax** [comment]
Sure. Should I just pick a cookbook at random and test this out? :)

**Comment by damacus** [comment]
Yup!

**Comment by xamebax** [comment]
Ok, I'm setting it up in the line cookbook first.

**Comment by josephholsten** [comment]
Looks like https://github.com/sous-chefs/line-cookbook/pull/65/files is a process to begin with

**Comment by josephholsten** [comment]
attempting to replicate and doc the process at https://github.com/sous-chefs/openvpn/pull/126

**Comment by damacus** [comment]
CircleCI seems more reliable at triggering Danger when it should. See the line cookbook for copy 'n pasta.

**Comment by JohnRoesler** [comment]
Specifically for setting up Danger on a repo using CircleCI:
- [CircleCI bit](https://github.com/sous-chefs/line/blob/fcaeca0/.circleci/config.yml#L9-L11)
- [Dangerfile](https://github.com/sous-chefs/line/blob/master/Dangerfile)

**Comment by josephholsten** [comment]
@damacus @JohnRoesler is this done? What's remaining?
