### ISSUE TITLE
Level of testing for sous-chef repos

### ISSUE THREAD

**Issue by jamietanna** [sous-chefs/meta#85]
I've noticed that a number of the sous-chef cookbooks don't have Rspec tests - is that something that you've decided not to do on purpose or is it something you'd be open to PRs for?

Additionally, would you be interested in further updates to ServerSpec/Inspec tests?

**Comment by damacus** [comment]
Hey @jamietanna 

We value Inspec > bats > chef-spec as a general rule. 

Often there isn't a lot of logic in the custom resources, which is where chefspec shines. Plus the support for chefspec with custom resources is usually not worth the pay back. 

The bonus with Inspec is we can write example cookbooks & test out the resources at the same time. The feedback cycle is, indeed slower but it's as close as running Chef in production is going to get.

**Comment by josephholsten** [comment]
At the moment, I'd be much more interested in making sure all our tests are actually passing. At the moment, this is not the case: https://travis-ci.org/sous-chefs/
