### ISSUE TITLE
AppVeyor Test Account for Sous-Chefs

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#86]
As noted in this PR and a number of other we need appveyor testing and not travis
https://github.com/sous-chefs/winrm/pull/8

**Comment by josephholsten** [comment]
also relevant: #72

**Comment by PowerSchill** [comment]
You don't have to have an account to see the results so maybe just an "org" account that can sign up and grant authorization to the repos?

**Comment by xorima** [comment]
Account is in the name of: SousChefs

**Comment by xorima** [comment]
We now have access
