### ISSUE TITLE
Moving Atom cookbook

### ISSUE THREAD

**Issue by damacus** [sous-chefs/meta#91]
https://github.com/mohitsethi/chef-atom/issues/16

I've asked to get the atom cookbook transferred here.

**Comment by MarkGibbons** [comment]
I use this cookbook in chefdk_bootstrap which installs atom as part of a customized development environment. Taking it over would really help.  I've got a PR in that rewrites the LWRP as a custom resource.

**Comment by damacus** [comment]
I use it in my workstation setup too.

Noticed your pr and thought why not.

**Comment by damacus** [comment]
https://twitter.com/souschefsorg/status/1035229831896723457

**Comment by MarkGibbons** [comment]
Atom was updated and merged.
