### ISSUE TITLE
NXLog cookbook

### ISSUE THREAD

**Issue by gdavison** [sous-chefs/meta#92]
The original cookbook at https://github.com/widgit-cookbooks/nxlog has been abandoned, and doesn’t work on Chef 13+. The owner didn’t respond on github or Twitter DM and tweet.
I started a fork at https://github.com/paybyphone/nxlog, which supports Chef 12-14, but figure this would be good for The sous-chefs.

**Comment by damacus** [comment]
@gdavison lets pulls this in! We'll transfer this on the hack day.
