### ISSUE TITLE
enable tests for more repos?

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#96]
https://github.com/sous-chefs/aptly
https://github.com/sous-chefs/control_groups
https://github.com/sous-chefs/dnsmasq
https://github.com/sous-chefs/gpg
https://github.com/sous-chefs/nexus

**Comment by damacus** [comment]
Gpg is broken right now, and until I can get it in a state ready to ship it isn't worth turning on.

**Comment by damacus** [comment]
The others we can do as I go along.

These are lower priority than everything else with broken tests right now though

**Comment by damacus** [comment]
If we want to add tests for repo X in the future, please open an issue there.
