### ISSUE TITLE
Make the website not horrible

### ISSUE THREAD

**Issue by josephholsten** [sous-chefs/meta#98]
What we need:
- no new content
- links to cookbooks in supermarket
- list of processes
- landing page that directs to slack, github, meeting invite
- not ugly as sin

**Comment by josephholsten** [comment]
landing page background image: https://flic.kr/p/J4CLVJ

**Comment by josephholsten** [comment]
contributing guide background: https://flic.kr/p/fqofd6

**Comment by josephholsten** [comment]
Decent themes:
- Landed https://html5up.net/uploads/demos/landed/elements.html
- Hyperspace https://html5up.net/uploads/demos/hyperspace/elements.html
And possibly, if we want to update photos every year:
- Spectral https://html5up.net/uploads/demos/spectral/elements.html
- Massively https://html5up.net/uploads/demos/massively/elements.html

**Comment by damacus** [comment]
Done ;)
